jobs:
   terrform:
   name: 'terraform'
   runs-on: self-hosted

   defaults:
   run:
   shell: bash

   step:
   name: Checkout 
   uses: action/checkout@v3

   - name: Steup Terraform
     uses: hashicorp/Setup Terraform@v2
     with:
     cli_config_credential_token:${{ secretes.TF_API_TOKEN }}

    - name: Terraform Init 
      run:terraform init

    - name:Teraform Format 
      run:terraform fmt -check

    - name:Terraform Plan
      run: terraform plan-input=false
      env:
          GOOGLE_CREDENTIALS: ${{secrets.GCP_SA_KEY }}


    - name: Terradform Apply  
      run:Terraform apply -auto-appprove -input=false
      env: 
          GOOGLE_CREDENTIALS: ${{secrets.GCP_SA_KEY }}
